package org.losi.vistas.procesos;

import java.util.HashMap;
import org.losi.controlador.acciones.Accion;
import org.losi.vistas.componentes.Formulario;
import org.losi.vistas.componentes.MyInternalFrame;

public class AltaEmpleadoFrame extends MyInternalFrame implements Formulario{
//public class AltaEmpleadoFrame extends javax.swing.JInternalFrame{
    /**
     * Creates new form AltaEmpleadoFrame
     */
    public AltaEmpleadoFrame() {
        initComponents();
        setMaximizable(false);
        setTitle("Alta de empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioEmpleado1 = new org.losi.vistas.procesos.FormularioEmpleado();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();

        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formularioEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(formularioEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Registro");
        Accion.getAccion("AltaEmpleado").ejecutar(this);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.losi.vistas.procesos.FormularioEmpleado formularioEmpleado1;
    private javax.swing.JButton jButton3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public HashMap<String,Object> getDatos() {
        return formularioEmpleado1.getDatos();
    }

    @Override
    public boolean isDatosOk() {
        return formularioEmpleado1.isDatosOk();
    }

    @Override
    public void setDatosOk(boolean valor) {
        formularioEmpleado1.setDatosOk(valor);
    }
}
